environment:
  PATH: 'C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%;C:\Rust\bin'
  RUST_BACKTRACE: 1

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.20.0-x86_64-pc-windows-gnu.msi"
  - msiexec /passive /i "rust-1.20.0-x86_64-pc-windows-gnu.msi" ADDLOCAL=Rustc,Cargo,Std INSTALLDIR=C:\Rust
  - bash -lc "pacman -S --noconfirm mingw-w64-x86_64-cmake"
  - rustc -V
  - cargo -V

build: false

test_script:
  - cd webrender_api
  - cargo test --verbose
  - cd ../webrender
  - cargo test --verbose
  - cd ../wrench
  - cargo test --verbose
