[package]
name = "webrender"
version = "0.1.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]

[target.i686-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.x86_64-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.arm-linux-androideabi.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.arm-unknown-linux-gnueabihf.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.aarch64-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[dependencies.ipc-channel]
git = "https://github.com/servo/ipc-channel"

[dependencies.webrender_traits]
git = "https://github.com/glennw/webrender_traits"

[dependencies.offscreen_gl_context]
git = "https://github.com/ecoal95/rust-offscreen-rendering-context"
branch = "webrender"

[dependencies]
gleam = "*"
euclid = "0.3"
time = "*"
fnv="*"
scoped_threadpool = "0.1.6"
app_units = "0.1"
lazy_static = "0.1"

[target.x86_64-apple-darwin.dependencies.core-text]
git = "https://github.com/servo/core-text-rs"

[target.x86_64-apple-darwin.dependencies]
core-graphics = "0.1"
