[package]
name = "webrender"
version = "0.1.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]

[target.i686-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.x86_64-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.arm-linux-androideabi.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.arm-unknown-linux-gnueabihf.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.aarch64-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.x86_64-pc-windows-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[dependencies.ipc-channel]
git = "https://github.com/servo/ipc-channel"

[dependencies.webrender_traits]
git = "https://github.com/servo/webrender_traits"

[dependencies.offscreen_gl_context]
git = "https://github.com/ecoal95/rust-offscreen-rendering-context"

#[dependencies.notify]
#git = "https://github.com/glennw/rsnotify.git"
#branch = "inotify-modify"

[dependencies]
gleam = "0.2"
euclid = {version = "0.6.2", features = ["plugins"]}
num = {version = "0.1.24", default-features = false}
time = "0.1"
fnv="1.0"
scoped_threadpool = "0.1.6"
app_units = {version = "0.2.1", features = ["plugins"]}
lazy_static = "0.1"

[target.x86_64-apple-darwin.dependencies]
core-graphics = "0.2"
core-text = "1.0"
