[workspace]
members = [
    "webrender",
    "webrender_api",
    "wrench",
]

[profile.release]
debug = true
panic = "abort"

[patch.crates-io]
serde = { git = "https://github.com/gankro/serde", branch = "deserialize_from_enums3" }
serde_derive = { git = "https://github.com/gankro/serde", branch = "deserialize_from_enums3", feature="deserialize_from" }
