[package]
name = "webrender"
version = "0.1.0"
authors = ["Glenn Watson <gw@intuitionlibrary.com>"]

[dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[dependencies]
gleam = "*"
libc = "*"
euclid = "0.2"
time = "*"
serde = "0.6"
serde_macros = "0.5"
fnv="*"
scoped_threadpool = "0.1.6"
app_units = "0.1"
simd = { git = "https://github.com/huonw/simd" }

[target.x86_64-apple-darwin.dependencies]
core-graphics = "*"
core-text = "*"

