[package]
name = "wrench"
version = "0.1.1"
authors = ["Vladimir Vukicevic <vladimir@pobox.com>"]
build = "build.rs"
workspace = ".."

[dependencies]
base64 = "0.3"
bincode = "0.6"
byteorder = "1.0"
euclid = "0.10"
gleam = "0.2"
glutin = "0.7"
app_units = "0.3"
image = "0.12"
clap = { version = "2", features = ["yaml"] }
lazy_static = "0.2"
yaml-rust = { git = "https://github.com/vvuk/yaml-rust" }
serde_json = "0.8"
time = "0.1"
crossbeam = "0.2"
osmesa-sys = { version = "0.1.2", optional = true }
osmesa-src = { git = "https://github.com/servo/osmesa-src", optional = true }

[features]
headless = [ "osmesa-sys", "osmesa-src" ]

[dependencies.webrender]
path = "../webrender"

[dependencies.webrender_traits]
path = "../webrender_traits"
default_features = false

[target.'cfg(target_os = "windows")'.dependencies]
dwrote = "0.1.2"

[target.'cfg(target_os = "linux")'.dependencies]
font-loader = "0.1.0"
